events {}
# Sección obligatoria de Nginx
# Maneja las conexiones entrantes
# Aquí se usan los valores por defecto

http {
    # Permite a Nginx identificar el tipo de archivo correcto
    # Ejemplo: .css → text/css, .js → application/javascript
    include /etc/nginx/mime.types;

    # Tipo de archivo por defecto si no se reconoce la extensión
    default_type application/octet-stream;

    server {
        # Nginx escucha en el puerto 80 (HTTP)
        # Cloudflare maneja el HTTPS externamente
        listen 80;

        # Carpeta raíz donde están los archivos de la web
        # Corresponde al volumen montado en docker-compose.yml
        root /usr/share/nginx/html;

        # Archivo que se muestra por defecto al entrar al sitio
        index index.html;

        # Sirve los archivos estáticos (HTML, CSS, JS)
        # Busca el archivo exacto → como carpeta → si no existe: 404
        location / {
            try_files $uri $uri/ =404;
        }

        # Redirige las peticiones del chatbot a FastAPI
        # El widget del chat hace fetch a /api/chat
        # Nginx lo redirige al contenedor cv_api en el puerto 8000
        # cv_api es el nombre del contenedor en docker-compose.yml
        # Los dos contenedores se comunican por la red interna de Docker
        location /api/ {
            proxy_pass http://cv_api:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}